//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_MatBangTTTM.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QL_MatBang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QL_MatBang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QL_MatBangTTTM.Resource.QL_MatBang", typeof(QL_MatBang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 Bờ Bao Tân Thắng, Sơn Kỳ, Tân Phú, Thành phố Hồ Chí Minh.
        /// </summary>
        internal static string DIACHI {
            get {
                return ResourceManager.GetString("DIACHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ký hợp đồng thuê mặt bằng.
        /// </summary>
        internal static string NOIDUNG {
            get {
                return ResourceManager.GetString("NOIDUNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn đã có hóa đơn tiền điện tháng {0} bạn hãy đóng hóa đơn trước mùng 1 của tháng sau nhé.
        /// </summary>
        internal static string NOIDUNGTHONGBAO {
            get {
                return ResourceManager.GetString("NOIDUNGTHONGBAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hóa đơn dịch vụ điện nước.
        /// </summary>
        internal static string TIEUDETHONGBAO {
            get {
                return ResourceManager.GetString("TIEUDETHONGBAO", resourceCulture);
            }
        }
    }
}
